"""baseline schema

Revision ID: bc84ae80b70f
Revises: 
Create Date: 2026-09-15 00:12:52.443904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc84ae80b70f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_runs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scenario_type', sa.String(), nullable=False),
    sa.Column('input_situation', sa.JSON(), nullable=False),
    sa.Column('tool_call_log', sa.JSON(), nullable=False),
    sa.Column('decision', sa.JSON(), nullable=True),
    sa.Column('validator_verdict', sa.JSON(), nullable=True),
    sa.Column('human_action', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budgets',
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('period', sa.String(), nullable=False),
    sa.Column('available_amount', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('category', 'period')
    )
    op.create_table('products',
    sa.Column('sku', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('unit_cost', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('sku')
    )
    op.create_table('demand_forecasts',
    sa.Column('product_sku', sa.String(), nullable=False),
    sa.Column('horizon_days', sa.Integer(), nullable=False),
    sa.Column('forecast_qty', sa.Integer(), nullable=False),
    sa.Column('recent_actual_sales_qty', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('product_sku')
    )
    op.create_table('inventory_snapshots',
    sa.Column('product_sku', sa.String(), nullable=False),
    sa.Column('on_hand_qty', sa.Integer(), nullable=False),
    sa.Column('storage_capacity_units', sa.Integer(), nullable=False),
    sa.Column('storage_used_units', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['product_sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('product_sku')
    )
    op.create_table('suppliers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('product_sku', sa.String(), nullable=False),
    sa.Column('lead_time_days', sa.Integer(), nullable=False),
    sa.Column('min_order_qty', sa.Integer(), nullable=False),
    sa.Column('reliability_score', sa.Float(), nullable=False),
    sa.Column('unit_price', sa.Float(), nullable=False),
    sa.Column('fulfillment_cap_qty', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_sku'], ['products.sku'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('purchase_orders',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('product_sku', sa.String(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('qty', sa.Integer(), nullable=False),
    sa.Column('fulfilled_qty', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expected_arrival', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_sku'], ['products.sku'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['suppliers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('purchase_orders')
    op.drop_table('suppliers')
    op.drop_table('inventory_snapshots')
    op.drop_table('demand_forecasts')
    op.drop_table('products')
    op.drop_table('budgets')
    op.drop_table('agent_runs')
    # ### end Alembic commands ###
